### PR TITLE
feat: Credential Dashboard fixes

### LINKED ISSUE #88: Misspelled word "Recepient"
**URL:** https://credentials.demos.verida.io/dashboard

Steps:

1. Go to https://credentials.demos.verida.io/dashboard
2. Click the New Result button

**_Actual Result:_** Field label is spelled as "Recepient"
**_Expected Result:_** It should be spelled as "Recipient"

2022-07-07_10h24_56

### LINKED ISSUE #89: Credential Details issues - No space in between Field Names, Repetitive word, Capitalized Case
**URL:** https://credentials.demos.verida.io/dashboard

**_Steps to replicate:_**

1. Go to https://credentials.demos.verida.io/dashboard
2. Select an Issued Test/Credential

**_Actual Result:_** 

- No space in between field names, (ie. "FullName:", "DateOfBirth:", "TestTimestamp:")
- Repetitive word  "Test Test" (ie. New COVID19 (PCR) _**Test Test**_ Result Is Available)
- Capitalized case (ie. New COVID19 (PCR) Test Test Result Is Available)

**_Expected Result:_** 

- Spelling issues should be fixed. 
- Remove the repetitive word
- Should use the correct case

2022-07-14_07h14_31

### LINKED ISSUE #90: Error when opening Schema URL for Hemoglobin Test and Syphilis (AB) Test
**_URL:_** https://credentials.demos.verida.io/dashboard

**_Steps to replicate:_**

1. Go to https://credentials.demos.verida.io/dashboard
2. Click the Schema tab
3. Click the schema Url for Haemoglobin Test: https://schemas.verida.io/health/pathology/tests/haemoglobin/v0.1.0/schema.json
4. Click the schema Url for Syphilis (AB) Test: https://common.verida.io/health/pathology/tests/syphilis/ab/v0.1.0/schema.json

**_Actual Result:_** Error when opening Schema URL for Hemoglobin Test and Syphilis (AB) Test
**_Expected Result:_** It should open the new tab without an error

2022-07-14_07h27_25

https://www.loom.com/share/a1a82f6539de4a0b929bf69570d1b860

### LINKED ISSUE #91: Schema - Misspelled word, Incorrect case
**URL:** https://credentials.demos.verida.io/dashboard

**Steps to replicate:**

1. Go to https://credentials.demos.verida.io/dashboard
2. Select Schema

**_Actual Result:_**

- Misspelled word "Haemoglobin Test"
- Incorrect case "schema Url :"

**_Expected Result:_** Words should be spelled as 'Hemoglobin Test' and 'Schema URL'

2022-07-14_08h12_24

### LINKED ISSUE #92: Redundant field - Name and Title
**_URL:_** https://credentials.demos.verida.io/dashboard

**_Steps to replicate:_**

1. Go to https://credentials.demos.verida.io/dashboard
2. Click Sent
3. Select an Issued Test/Credential

**_Actual Result:_** Name and Fields shows the same value

**_Expected Result:_**  The value for these fields is from the 'Document Type' field. Is this intentional? Shouldn't it just be displayed in a single field?

2022-07-14_08h36_12

2022-07-14_08h30_30

### LINKED ISSUE #93: Add pop up warning when deleting a schema
**_URL:_** https://credentials.demos.verida.io/dashboard

**_Steps to replicate:_**

1. Go to https://credentials.demos.verida.io/dashboard
2. Click Schema
3. Select a Schema
4. Click the 'Delete' button

**_Actual Result:_** Schema is automatically deleted.

**_Expected Result:_** A pop up warning should appear before deleting a schema (ie. "Are you sure you want to delete this schema?". Add 'Cancel' and 'Delete' button)

2022-07-14_08h49_30

### LINKED ISSUE #94: Add a better error message
**_URL:_** https://credentials.demos.verida.io/dashboard

**_Steps to replicate:_**

1. Go to https://credentials.demos.verida.io/dashboard
2. Select Schema
3. Click the 'Add Schema' button
4. Enter an invalid Schema URL

**_Actual Result:_** Error message just shows "undefined"

**_Expected Result:_** Add a better error message. Keep it clear and concise

2022-07-14_09h03_21

### LINKED ISSUE #96: Add a success pop up message when the New Result form has been sent
**_URL:_** https://credentials.demos.verida.io/dashboard

**_Steps to replicate:_**

1. Go to https://credentials.demos.verida.io/dashboard
2. lClick Sent
3. Click the 'New Result' button
4. Fill out all the required fields
5. Click the Send Credential button

**_Actual Result:_** 

- The New Result form including the fields and buttons are disabled and appears frozen.
- No pop up message displayed

**_Expected Result:_** A success pop-up message should appear when the form is successfully sent

https://www.loom.com/share/70275f68e6454c32b2edd70274ec679b

2022-07-14_09h53_25

### LINKED ISSUE #97: The Date of Birth cannot be in the future.
**_URL:_** https://credentials.demos.verida.io/dashboard

**_Steps to replicate:_**

1. Go to https://credentials.demos.verida.io/dashboard
2. Click Sent
3. Click the 'New Result' button
4. Click the Date Picker for the Date of Birth field.

**_Actual Result:_** Future dates are accepted.

**_Expected Result:_** The values on the Date of Birth field should not be in the future.

2022-07-14_10h14_25

2022-07-14_10h14_18

### LINKED ISSUE #98: DidJwtVc is shown on the Credential Details for Australian Basic KYC and Cholesterol (Total) Test
**_URL:_** https://credentials.demos.verida.io/dashboard

**_Steps to replicate:_**

1. Go to https://credentials.demos.verida.io/dashboard
2. Click Sent
3. Select a Australian Basic KYC
4. Select a Cholesterol (Total) Test

**_Actual Result:_** 

- DidJwtVc is shown on the Credential Details for Australian Basic KYC and Cholesterol (Total) Test only
- It takes a lot of space on the Credential Details screen

**_Expected Result:_** It is only shown on two (2) results. Is it necessary to display it as it takes too much space on the screen?

2022-07-14_10h27_31

### LINKED ISSUE #99: No notifications received when Credential has been successfully issued
**_URL:_** https://credentials.demos.verida.io/dashboard

**_Steps to replicate:_**

1. Go to https://credentials.demos.verida.io/dashboard
2. Click Sent
3. Click the 'New Result' button
4. Fill out all required fields.
5. Enter Recipient DID
6. Click Send Credential button

**_Actual Result:_** 

- No notifications received when Credential has been successfully issued
- New Credentials can only be viewed on the Inbox

**_Expected Result:_** A notification should show up when a new credential has been issued.

### PR DESCRIPTION
**Pull request by cmcWebCode40**
### Tasks
- Added vue notify toaster packages
- Modified vue-date-picker to not allowed future DOB
- Removed the DidJWTVc field from credential detail views

### See Demo :
https://www.loom.com/share/5c364831381e41bab9ec3b4a39c9dc02

closes #99 

closes #98 

closes #97

closes #91

closes #92

closes #93

closes #96

closes #88

closes #89

closes #90

closes #94

### CODE REVIEW

**Comment by RochelleBondoc** [comment]
Hi @cmcWebCode40 , has this been merged and deployed so I can be able to test it?

File: frontend/src/components/particles/CredentialHeader.vue [hunk 1]
```diff
@@ -59,7 +50,7 @@
             />
           </ValidationProvider>
         </template>
-        <v-date-picker v-model="main.dob" scrollable>
+        <v-date-picker v-model="main.dob" scrollable max="2021-01-20">
```
Comment (aurelticot) [inline frontend/src/components/particles/CredentialHeader.vue:53]: Probably cleaner to set it to today's date rather than hardcoded to a certain date

**Review by aurelticot — CHANGES_REQUESTED** [review]
See my inline comment about max date for date-picker.

Also, I'm challenging the need to hide the jwt. See my comment in #98

**Comment by cmcWebCode40** [comment]
@RochelleBondoc,

please see @aurelticot  comment regarding hiding the didJwtVc value, it's actually for reference purposes.

File: backend/src/helpers/VeridaHelper.ts [hunk 2]
```diff
@@ -183,7 +183,7 @@ export default class VeridaHelper {
 
       return json;
     } catch (error) {
-      console.log({ error });
+      throw new Error(error);
```
Comment (dmty) [inline backend/src/helpers/VeridaHelper.ts:186]: If you just throwing the same error further you could simply delete the try..catch

File: frontend/src/components/modals/NewSchemaDialog.vue [hunk 3]
```diff
@@ -97,7 +97,10 @@ export default {
         this.schemaUrl = "";
         this.closeModal();
       } catch (error) {
-        this.error = error;
+        this.error = {
+          message:
+            "unable to add schema url (ensure the url is a valid schema url",
```
Comment (dmty) [inline frontend/src/components/modals/NewSchemaDialog.vue:102]: Do we have any standard approach to message formatting? Might be better to start sentence with capital

File: frontend/src/store/modules/credential.js [hunk 4]
```diff
@@ -1,50 +1,50 @@
 const state = {
-  list: [],
+	list: [],
```
Comment (dmty) [inline frontend/src/store/modules/credential.js:2]: Wonder what's the reason for the formatting change? It's getting different across the files 🤔

**Review by dmty — APPROVED** [review]
Put a couple of comments, don't see anything blocking. Would suggest to add prettier to have something standard, also would get less complains for Github Actions

**Comment by aurelticot** [comment]
There are too many unrelated issues in this PR

More importantly, there are commits handling too many unrelated issues.
I tried to isolate the changes for #92 which is expected to be on 1 file, but the one commit `619a8e2` closes 5 unrelated issues on 12 files!

Please @cmcWebCode40 at least make one commit per related topic.

**Comment by cmcWebCode40** [comment]
> There are too many unrelated issues in this PR
> 
> More importantly, there are commits handling too many unrelated issues. I tried to isolate the changes for #92 which is expected to be on 1 file, but the one commit `619a8e2` closes 5 unrelated issues on 12 files!
> 
> Please @cmcWebCode40 at least make one commit per related topic.

@aurelticot ,

I understand your point on making one commit per related issue, but this case, most of the issues @RochelleBondoc  created were related issues and mostly minor fixes some were changing texts , that was why i had to fix most of them in one commit .

moving forward i will separate the issues into one commit , where its a major or minor fix .

File: backend/src/helpers/VeridaHelper.ts (hunk 2 above)
Comment (cmcWebCode40) [reply backend/src/helpers/VeridaHelper.ts:184]: resolved

File: frontend/src/components/cards/Result.vue [hunk 5]
```diff
@@ -32,6 +32,16 @@ const { mapMutations: mapSystemMutations } = createNamespacedHelpers("system");
 export default {
   name: "Result",
   props: ["result"],
+  data() {
+    return {
+      schemaProps: {},
+    };
+  },
+  mounted() {
+    if (this.result && this.result.schema) {
```
[the remark this answers is not in the document]
Comment (cmcWebCode40) [reply frontend/src/components/cards/Result.vue]: resolved

File: frontend/src/store/modules/credential.js (hunk 4 above)
Comment (cmcWebCode40) [reply frontend/src/store/modules/credential.js:2]: yes, this is because we have not fully integrated eslint setup

File: frontend/src/components/modals/ResultDialog.vue [hunk 6]
```diff
@@ -132,14 +131,15 @@ export default {
       const form = this.$refs.fields.form;
 
       this.setDateOfBirth(form, data);
-      data.name = form.fullName;
+      form.lastName = "eriueiruieu";
```
[the remark this answers is not in the document]
Comment (cmcWebCode40) [reply frontend/src/components/modals/ResultDialog.vue]: no, removed
